### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by KingMatrix1989** [m-esm/hakamo#1]
### User Story
As a user, I want to be able to register and log in to the system securely.

### Tasks
- [ ] Implement user registration with email verification.
- [ ] Set up JWT-based authentication for login sessions.
- [ ] Create UI for login and registration forms.

**Comment by KingMatrix1989** [comment]
sdfsdfsdf
